name: flutter_link_previewer
description: >
  URL preview extracted from the provided text with
  basic customization and ability to render from cached data.
version: 2.0.8
homepage: https://github.com/flyerhq/flutter_link_previewer

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  #flutter_chat_types: ^2.1.5
  flutter_chat_types:
    git:
      url: https://github.com/ntsmac/flutter_chat_types.git
      ref: audio_message_types

  flutter_linkify: ^5.0.2
  html: ^0.15.0
  http: ^1.2.0
  linkify: ^4.0.0
  meta: ^1.3.0
  url_launcher: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
